"""Demo Streamlit app for cortex-agents-client UI testing.

Runs a fully functional chatbot without a real Snowflake connection by
pre-seeding ``st.session_state`` with :class:`~streamlit_demo.mock_thread.MockClient`
and :class:`~streamlit_demo.mock_thread.MockThread` objects.

Because :func:`~cortex_agents_client.st.session.init_session` is idempotent
(it checks whether the session state keys already exist before creating
anything), the chatbot uses the mocks directly without any patching.

Run from the project root::

    uv run streamlit run streamlit_demo/app.py

No ``.streamlit/secrets.toml`` or Snowflake credentials are required.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Logging — configure once at app entry point, before any library imports.
# Emits to stdout so Snowflake's container runtime captures logs in the event
# table and shows them in the Snowsight live-log pane.
# See https://docs.snowflake.com/en/developer-guide/streamlit/features/logging-tracing
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    stream=sys.stdout,
)

# Ensure the project root is on sys.path so the library is importable when
# running the app directly with `streamlit run streamlit_demo/app.py`.
_project_root = Path(__file__).parent.parent
if str(_project_root) not in sys.path:
    sys.path.insert(0, str(_project_root))

# Ensure this package's directory is on sys.path for the relative import below.
_demo_dir = Path(__file__).parent
if str(_demo_dir) not in sys.path:
    sys.path.insert(0, str(_demo_dir))

import streamlit as st
from mock_thread import (  # noqa: E402 — sys.path must be set first
    SCENARIO_HINTS,
    SCENARIO_NAMES,
    MockClient,
    MockThread,
)

from cortex_agents_client.st.chatbot import StreamlitChatbot

# ---------------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="Cortex Agents Client — UI Demo",
    page_icon=":material/smart_toy:",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Sidebar controls
# ---------------------------------------------------------------------------

st.sidebar.header("Demo controls")

selected_scenario = st.sidebar.selectbox(
    "Scenario",
    options=SCENARIO_NAMES,
    help="Each scenario exercises a different set of SSE event types.",
)

st.sidebar.divider()

selected_mode = st.sidebar.radio(
    "Chat mode",
    options=["fullpage", "embedded", "dialog"],
    index=0,
    help=(
        "**fullpage**: ``st.chat_input`` pinned to the page bottom. "
        "**embedded**: fixed-height container + inline ``st.chat_input`` "
        "(Streamlit ≥ 1.59), works inside columns and dialogs. "
        "**dialog**: full-width dashboard with a trigger button that opens the "
        "chatbot in a persistent modal overlay (``@st.dialog``, ``dismissible=False``)."
    ),
)

st.sidebar.divider()

show_thinking = st.sidebar.toggle(
    "Show reasoning",
    value=True,
    help="Render ThinkingEvent blocks in a collapsible expander.",
)
show_tool_status = st.sidebar.toggle(
    "Show tool status",
    value=True,
    help="Show compact status spinners during tool execution.",
)
accept_file = st.sidebar.toggle(
    "Allow file attachments",
    value=False,
    help=(
        "Enables the file-attachment button on ``st.chat_input``. "
        "Uploaded files are displayed in the chat but **not** sent to the agent "
        "(demo only)."
    ),
)
accept_audio = st.sidebar.toggle(
    "Allow voice input",
    value=False,
    help="Enables the microphone button on ``st.chat_input``.",
)

if selected_mode == "embedded":
    chat_height = st.sidebar.slider(
        "Chat height (px)",
        min_value=200,
        max_value=700,
        value=420,
        step=10,
        help="Height of the scrollable message area in embedded mode.",
    )
elif selected_mode == "dialog":
    chat_height = st.sidebar.slider(
        "Dialog chat height (px)",
        min_value=300,
        max_value=600,
        value=480,
        step=10,
        help="Height of the scrollable message area inside the dialog overlay.",
    )
else:
    chat_height = 420

st.sidebar.divider()
st.sidebar.caption(
    "This demo uses pre-canned SSE event streams — no Snowflake account needed. "
    "All responses are generated by `streamlit_demo/mock_thread.py`. "
    "Skeleton loading state is visible on slower scenarios (Thinking, Kitchen sink)."
)

# ---------------------------------------------------------------------------
# Session state: inject mock client and thread
# ---------------------------------------------------------------------------

# The chatbot uses the prefix "_demo" for its session state keys:
#   _demo_client, _demo_thread, _demo_messages
# init_session() checks "if key not in st.session_state" before creating anything,
# so pre-seeding these keys causes it to use the mocks directly.

_PREFIX = "_demo"
_CLIENT_KEY = f"{_PREFIX}_client"
_THREAD_KEY = f"{_PREFIX}_thread"
_MESSAGES_KEY = f"{_PREFIX}_messages"
_LAST_SCENARIO_KEY = f"{_PREFIX}_last_scenario"

# Detect scenario changes and reset so the new scenario takes effect.
current_id = (selected_scenario, selected_mode)
if st.session_state.get(_LAST_SCENARIO_KEY) != current_id:
    for k in (_CLIENT_KEY, _THREAD_KEY, _MESSAGES_KEY):
        st.session_state.pop(k, None)
    st.session_state[_LAST_SCENARIO_KEY] = current_id

if _CLIENT_KEY not in st.session_state:
    st.session_state[_CLIENT_KEY] = MockClient(selected_scenario)
if _THREAD_KEY not in st.session_state:
    st.session_state[_THREAD_KEY] = MockThread(selected_scenario)
if _MESSAGES_KEY not in st.session_state:
    st.session_state[_MESSAGES_KEY] = []

# ---------------------------------------------------------------------------
# Session state: popup dialog chatbot (independent prefix and history)
# ---------------------------------------------------------------------------

_POPUP_PREFIX = "_popup"
_POPUP_CLIENT_KEY = f"{_POPUP_PREFIX}_client"
_POPUP_THREAD_KEY = f"{_POPUP_PREFIX}_thread"
_POPUP_MESSAGES_KEY = f"{_POPUP_PREFIX}_messages"
_POPUP_LAST_SCENARIO_KEY = f"{_POPUP_PREFIX}_last_scenario"

if st.session_state.get(_POPUP_LAST_SCENARIO_KEY) != selected_scenario:
    for k in (_POPUP_CLIENT_KEY, _POPUP_THREAD_KEY, _POPUP_MESSAGES_KEY):
        st.session_state.pop(k, None)
    st.session_state[_POPUP_LAST_SCENARIO_KEY] = selected_scenario

if _POPUP_CLIENT_KEY not in st.session_state:
    st.session_state[_POPUP_CLIENT_KEY] = MockClient(selected_scenario)
if _POPUP_THREAD_KEY not in st.session_state:
    st.session_state[_POPUP_THREAD_KEY] = MockThread(selected_scenario)
if _POPUP_MESSAGES_KEY not in st.session_state:
    st.session_state[_POPUP_MESSAGES_KEY] = []

if "chat_dialog_open" not in st.session_state:
    st.session_state.chat_dialog_open = False

# ---------------------------------------------------------------------------
# Chatbot factory
# ---------------------------------------------------------------------------


def _make_bot() -> StreamlitChatbot:
    """Returns a configured :class:`~cortex_agents_client.st.chatbot.StreamlitChatbot`.

    Returns:
        A chatbot instance ready to render.
    """
    return StreamlitChatbot(
        # account_url and auth are ignored — init_session() uses the pre-seeded
        # MockClient from session state and never constructs a real client.
        account_url="mock://localhost",
        auth="mock_token",
        agent_path="DEMO.DEMO.DEMO_AGENT",
        mode=selected_mode if selected_mode != "dialog" else "embedded",
        height=chat_height,
        show_thinking=show_thinking,
        show_tool_status=show_tool_status,
        new_conversation_button=True,
        origin_application="ui_demo",
        session_key_prefix=_PREFIX,
        accept_file="multiple" if accept_file else False,
        accept_audio=accept_audio,
    )


@st.dialog("Ask the agent", width="large", dismissible=False, icon=":material/smart_toy:")
def _chat_dialog() -> None:
    """Renders the chatbot inside a persistent modal dialog overlay."""
    with st.container(horizontal_alignment="right"):
        if st.button("Close", icon=":material/close:", type="tertiary"):
            st.session_state.chat_dialog_open = False
            st.rerun()
    StreamlitChatbot(
        account_url="mock://localhost",
        auth="mock_token",
        agent_path="DEMO.DEMO.DEMO_AGENT",
        mode="embedded",
        height=chat_height,
        show_thinking=show_thinking,
        show_tool_status=show_tool_status,
        new_conversation_button=True,
        origin_application="ui_demo",
        session_key_prefix=_POPUP_PREFIX,
        accept_file="multiple" if accept_file else False,
        accept_audio=accept_audio,
    ).render()


# ---------------------------------------------------------------------------
# Scenario hint banner
# ---------------------------------------------------------------------------

hint = SCENARIO_HINTS.get(selected_scenario, "")
if hint:
    st.info(hint, icon=":material/info:")

# ---------------------------------------------------------------------------
# Render: fullpage mode
# ---------------------------------------------------------------------------

if selected_mode == "fullpage":
    st.title("Cortex Agents Client — UI Demo")
    st.caption(
        f"Scenario: **{selected_scenario}** · Mode: **{selected_mode}** · "
        f"Reasoning: **{'on' if show_thinking else 'off'}** · "
        f"Tool status: **{'on' if show_tool_status else 'off'}**"
    )
    _make_bot().render()

elif selected_mode == "embedded":
    st.title("Dashboard + Embedded Chat")
    st.caption(
        f"Scenario: **{selected_scenario}** · "
        f"Reasoning: **{'on' if show_thinking else 'off'}** · "
        f"Tool status: **{'on' if show_tool_status else 'off'}**"
    )

    dash_col, chat_col = st.columns([3, 2], gap="large")

    with dash_col:
        st.subheader(":material/bar_chart: Q1 2026 Regional Revenue")
        st.bar_chart(
            {
                "North America": 452000,
                "Europe": 381000,
                "Asia Pacific": 294000,
                "Latin America": 183000,
                "ME & Africa": 97000,
            },
            color="#3B82F6",
            use_container_width=True,
        )

        metric_a, metric_b, metric_c = st.columns(3)
        metric_a.metric("Total revenue", "$1.41M", "+18% vs Q4")
        metric_b.metric("Total orders", "5,492", "+12% vs Q4")
        metric_c.metric("Avg order value", "$257", "+5% vs Q4")

        st.subheader(":material/table: Top products")
        st.dataframe(
            {
                "Product": ["Widget A", "Widget B", "Widget C", "Widget D"],
                "Units sold": [1_240, 980, 650, 440],
                "Revenue": ["$248K", "$196K", "$130K", "$88K"],
                "Margin": ["42%", "38%", "45%", "31%"],
            },
            hide_index=True,
            use_container_width=True,
        )

    with chat_col:
        st.subheader(":material/smart_toy: Ask the agent")
        _make_bot().render()

elif selected_mode == "dialog":
    header_col, btn_col = st.columns([5, 1], vertical_alignment="bottom")
    with header_col:
        st.title("Dashboard")
        st.caption(
            f"Scenario: **{selected_scenario}** · "
            f"Reasoning: **{'on' if show_thinking else 'off'}** · "
            f"Tool status: **{'on' if show_tool_status else 'off'}**"
        )
    with btn_col:
        if st.button(
            "Ask the agent",
            icon=":material/smart_toy:",
            type="primary",
            use_container_width=True,
        ):
            st.session_state.chat_dialog_open = True

    st.subheader(":material/bar_chart: Q1 2026 Regional Revenue")
    st.bar_chart(
        {
            "North America": 452000,
            "Europe": 381000,
            "Asia Pacific": 294000,
            "Latin America": 183000,
            "ME & Africa": 97000,
        },
        color="#3B82F6",
        use_container_width=True,
    )

    metric_a, metric_b, metric_c = st.columns(3)
    metric_a.metric("Total revenue", "$1.41M", "+18% vs Q4")
    metric_b.metric("Total orders", "5,492", "+12% vs Q4")
    metric_c.metric("Avg order value", "$257", "+5% vs Q4")

    st.subheader(":material/table: Top products")
    st.dataframe(
        {
            "Product": ["Widget A", "Widget B", "Widget C", "Widget D"],
            "Units sold": [1_240, 980, 650, 440],
            "Revenue": ["$248K", "$196K", "$130K", "$88K"],
            "Margin": ["42%", "38%", "45%", "31%"],
        },
        hide_index=True,
        use_container_width=True,
    )

# ---------------------------------------------------------------------------
# Dialog overlay — opened from any mode via chat_dialog_open session state
# ---------------------------------------------------------------------------

if st.session_state.chat_dialog_open:
    _chat_dialog()

# ---------------------------------------------------------------------------
# Footer
# ---------------------------------------------------------------------------

st.divider()
st.caption(
    ":material/code: "
    "[`streamlit_demo/app.py`](streamlit_demo/app.py) · "
    "[`streamlit_demo/mock_thread.py`](streamlit_demo/mock_thread.py) · "
    "[`cortex_agents_client/st/chatbot.py`](cortex_agents_client/st/chatbot.py)"
)
