"""Models package for the Cortex Agents library."""

from streamlit_cortex_agents.client.models.agent import (
    Agent,
    AgentInstructions,
    AgentProfile,
    BudgetConfig,
    ModelConfig,
    OrchestrationConfig,
    Tool,
    ToolSpec,
)
from streamlit_cortex_agents.client.models.events import (
    AnalystDeltaEvent,
    ChartEvent,
    ErrorEvent,
    MetadataEvent,
    RunMetadata,
    SSEEvent,
    StatusEvent,
    SuggestedQueriesEvent,
    TableEvent,
    TextAnnotationEvent,
    TextDeltaEvent,
    TextEvent,
    ThinkingDeltaEvent,
    ThinkingEvent,
    ToolResultEvent,
    ToolResultStatusEvent,
    ToolUseEvent,
    UnknownEvent,
    WarningEvent,
)
from streamlit_cortex_agents.client.models.thread import (
    StoredMessage,
    ThreadDetail,
    ThreadMessage,
    ThreadMetadata,
)

__all__ = [
    # Agent models
    "Agent",
    "AgentProfile",
    "AgentInstructions",
    "BudgetConfig",
    "ModelConfig",
    "OrchestrationConfig",
    "Tool",
    "ToolSpec",
    # Event models
    "SSEEvent",
    "TextDeltaEvent",
    "TextEvent",
    "TextAnnotationEvent",
    "ThinkingDeltaEvent",
    "ThinkingEvent",
    "ToolUseEvent",
    "ToolResultEvent",
    "ToolResultStatusEvent",
    "AnalystDeltaEvent",
    "TableEvent",
    "ChartEvent",
    "StatusEvent",
    "SuggestedQueriesEvent",
    "WarningEvent",
    "ErrorEvent",
    "MetadataEvent",
    "RunMetadata",
    "UnknownEvent",
    # Thread models
    "ThreadMetadata",
    "ThreadMessage",
    "ThreadDetail",
    "StoredMessage",
]
