"""Demo Streamlit app for streamlit-cortex-agents UI testing.

Runs a fully functional chatbot without a real Snowflake connection by
pre-seeding ``st.session_state`` with :class:`~mock_thread.MockClient`
and :class:`~mock_thread.MockThread` objects.

Because :func:`~streamlit_cortex_agents.chat.session.init_session` is idempotent
(it checks whether the session state keys already exist before creating
anything), the chatbot uses the mocks directly without any patching.

Run from the project root::

    uv run streamlit run examples/demo/app.py

No ``.streamlit/secrets.toml`` or Snowflake credentials are required.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Logging — configure once at app entry point, before any library imports.
# Emits to stdout so Snowflake's container runtime captures logs in the event
# table and shows them in the Snowsight live-log pane.
# See https://docs.snowflake.com/en/developer-guide/streamlit/features/logging-tracing
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    stream=sys.stdout,
)

# The library is imported from the installed package (``uv sync`` installs it
# in editable mode from src/). Put this directory on sys.path for the
# mock_thread import below.
_demo_dir = Path(__file__).parent
if str(_demo_dir) not in sys.path:
    sys.path.insert(0, str(_demo_dir))

import streamlit as st  # noqa: E402 — sys.path must be set first
from mock_thread import (  # noqa: E402 — sys.path must be set first
    SCENARIO_HINTS,
    SCENARIO_NAMES,
    MockClient,
    MockThread,
)

from streamlit_cortex_agents.chat import CortexAgentChat  # noqa: E402

# ---------------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="Cortex Agents Client — UI Demo",
    page_icon=":material/smart_toy:",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Shared sidebar — rendered on every page
# ---------------------------------------------------------------------------

st.sidebar.header("Demo controls")

selected_scenario = st.sidebar.selectbox(
    "Scenario",
    options=SCENARIO_NAMES,
    help="Each scenario exercises a different set of SSE event types.",
)

st.sidebar.divider()

show_thinking = st.sidebar.toggle(
    "Show reasoning",
    value=True,
    help="Render ThinkingEvent blocks as steps in the Reasoning timeline.",
)
show_tool_status = st.sidebar.toggle(
    "Show tool status",
    value=True,
    help="Show tool calls as steps in the Reasoning timeline.",
)
accept_file = st.sidebar.toggle(
    "Allow file attachments",
    value=False,
    help=(
        "UI only — not yet implemented. "
        "Enables the file-attachment button on ``st.chat_input``, but uploaded files "
        "are not sent to the agent."
    ),
)
accept_audio = st.sidebar.toggle(
    "Allow voice input",
    value=False,
    help=(
        "UI only — not yet implemented. "
        "Enables the microphone button on ``st.chat_input``, but audio is not "
        "transcribed or sent to the agent."
    ),
)
st.sidebar.caption(
    ":material/construction: **File attachments** and **voice input** are UI previews "
    "only — backend support is not yet implemented."
)

st.sidebar.divider()
st.sidebar.caption(
    "This demo uses pre-canned SSE event streams — no Snowflake account needed. "
    "All responses are generated by `examples/demo/mock_thread.py`."
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _seed_state(prefix: str) -> None:
    """Pre-seeds mock client, thread, and messages into session state.

    Uses ``selected_scenario`` from the outer scope. Clears and re-seeds when
    the scenario changes so the new scenario takes effect immediately.

    Args:
        prefix: Session state key prefix (e.g. ``"_fp"``).
    """
    client_key = f"{prefix}_client"
    thread_key = f"{prefix}_thread"
    messages_key = f"{prefix}_messages"
    last_key = f"{prefix}_last_scenario"

    if st.session_state.get(last_key) != selected_scenario:
        for k in (client_key, thread_key, messages_key):
            st.session_state.pop(k, None)
        st.session_state[last_key] = selected_scenario

    st.session_state.setdefault(client_key, MockClient(selected_scenario))
    st.session_state.setdefault(thread_key, MockThread(selected_scenario))
    st.session_state.setdefault(messages_key, [])


def _hint() -> None:
    """Renders the scenario hint banner if one is defined."""
    hint = SCENARIO_HINTS.get(selected_scenario, "")
    if hint:
        st.info(hint, icon=":material/info:")


def _caption(**kwargs: str) -> None:
    """Renders the status caption line."""
    parts = [f"Scenario: **{selected_scenario}**"]
    parts += [f"{k}: **{v}**" for k, v in kwargs.items()]
    st.caption(" · ".join(parts))


def _footer() -> None:
    """Renders the source-file footer."""
    st.divider()
    st.caption(
        ":material/code: "
        "[`examples/demo/app.py`](examples/demo/app.py) · "
        "[`examples/demo/mock_thread.py`](examples/demo/mock_thread.py) · "
        "[`src/streamlit_cortex_agents/chat/chatbot.py`](src/streamlit_cortex_agents/chat/chatbot.py)"
    )


# ---------------------------------------------------------------------------
# Pages
# ---------------------------------------------------------------------------


def page_fullpage() -> None:
    """Full-page mode: st.chat_input pinned to the page bottom."""
    _seed_state("_fp")
    _hint()
    st.title("Cortex Agents Client — UI Demo")
    _caption(
        Reasoning="on" if show_thinking else "off",
        **{"Tool status": "on" if show_tool_status else "off"},
    )
    CortexAgentChat(
        account_url="mock://localhost",
        auth="mock_token",
        agent_path="DEMO.DEMO.DEMO_AGENT",
        mode="fullpage",
        show_thinking=show_thinking,
        show_tool_status=show_tool_status,
        new_conversation_button=True,
        origin_application="ui_demo",
        session_key_prefix="_fp",
        accept_file="multiple" if accept_file else False,
        accept_audio=accept_audio,
    ).render()
    _footer()


def page_embedded() -> None:
    """Embedded mode: fixed-height chat alongside a dashboard."""
    _seed_state("_emb")
    chat_height = st.sidebar.slider(
        "Chat height (px)",
        min_value=200,
        max_value=700,
        value=420,
        step=10,
        help="Height of the scrollable message area.",
    )
    _hint()
    st.title("Dashboard + Embedded Chat")
    _caption(
        Reasoning="on" if show_thinking else "off",
        **{"Tool status": "on" if show_tool_status else "off"},
    )

    dash_col, chat_col = st.columns([3, 2], gap="large")

    with dash_col:
        st.subheader(":material/bar_chart: Q1 2026 Regional Revenue")
        st.bar_chart(
            {
                "North America": 452000,
                "Europe": 381000,
                "Asia Pacific": 294000,
                "Latin America": 183000,
                "ME & Africa": 97000,
            },
            color="#3B82F6",
            width="stretch",
        )

        metric_a, metric_b, metric_c = st.columns(3)
        metric_a.metric("Total revenue", "$1.41M", "+18% vs Q4")
        metric_b.metric("Total orders", "5,492", "+12% vs Q4")
        metric_c.metric("Avg order value", "$257", "+5% vs Q4")

        st.subheader(":material/table: Top products")
        st.dataframe(
            {
                "Product": ["Widget A", "Widget B", "Widget C", "Widget D"],
                "Units sold": [1_240, 980, 650, 440],
                "Revenue": ["$248K", "$196K", "$130K", "$88K"],
                "Margin": ["42%", "38%", "45%", "31%"],
            },
            hide_index=True,
            width="stretch",
        )

    with chat_col:
        st.subheader(":material/smart_toy: Ask the agent")
        CortexAgentChat(
            account_url="mock://localhost",
            auth="mock_token",
            agent_path="DEMO.DEMO.DEMO_AGENT",
            mode="embedded",
            height=chat_height,
            show_thinking=show_thinking,
            show_tool_status=show_tool_status,
            new_conversation_button=True,
            origin_application="ui_demo",
            session_key_prefix="_emb",
            accept_file="multiple" if accept_file else False,
            accept_audio=accept_audio,
        ).render()

    _footer()


def page_dialog() -> None:
    """Dialog mode: full dashboard with a button that opens a modal chatbot."""
    _seed_state("_dlg_popup")

    if "chat_dialog_open" not in st.session_state:
        st.session_state.chat_dialog_open = False

    @st.dialog("Ask the agent", width="large", dismissible=False, icon=":material/smart_toy:")
    def _chat_dialog() -> None:
        with st.container(horizontal_alignment="right"):
            if st.button("Close", icon=":material/close:", type="tertiary"):
                st.session_state.chat_dialog_open = False
                st.rerun()
        CortexAgentChat(
            account_url="mock://localhost",
            auth="mock_token",
            agent_path="DEMO.DEMO.DEMO_AGENT",
            mode="embedded",
            # Fill the viewport; 440px covers the dialog title, the Close
            # and New conversation buttons and the chat input.
            height="calc(100vh - 440px)",
            show_thinking=show_thinking,
            show_tool_status=show_tool_status,
            new_conversation_button=True,
            origin_application="ui_demo",
            session_key_prefix="_dlg_popup",
            accept_file="multiple" if accept_file else False,
            accept_audio=accept_audio,
        ).render()

    _hint()

    header_col, btn_col = st.columns([5, 1], vertical_alignment="bottom")
    with header_col:
        st.title("Dashboard")
        _caption(
            Reasoning="on" if show_thinking else "off",
            **{"Tool status": "on" if show_tool_status else "off"},
        )
    with btn_col:
        if st.button(
            "Ask the agent",
            icon=":material/smart_toy:",
            type="primary",
            width="stretch",
        ):
            st.session_state.chat_dialog_open = True

    st.subheader(":material/bar_chart: Q1 2026 Regional Revenue")
    st.bar_chart(
        {
            "North America": 452000,
            "Europe": 381000,
            "Asia Pacific": 294000,
            "Latin America": 183000,
            "ME & Africa": 97000,
        },
        color="#3B82F6",
        width="stretch",
    )

    metric_a, metric_b, metric_c = st.columns(3)
    metric_a.metric("Total revenue", "$1.41M", "+18% vs Q4")
    metric_b.metric("Total orders", "5,492", "+12% vs Q4")
    metric_c.metric("Avg order value", "$257", "+5% vs Q4")

    st.subheader(":material/table: Top products")
    st.dataframe(
        {
            "Product": ["Widget A", "Widget B", "Widget C", "Widget D"],
            "Units sold": [1_240, 980, 650, 440],
            "Revenue": ["$248K", "$196K", "$130K", "$88K"],
            "Margin": ["42%", "38%", "45%", "31%"],
        },
        hide_index=True,
        width="stretch",
    )

    if st.session_state.chat_dialog_open:
        _chat_dialog()

    _footer()


def page_code() -> None:
    """Code examples page: shows copy-paste snippets for each chat mode."""
    st.title("Code examples")
    st.caption("Copy-paste snippets for each layout mode. Replace the placeholder values with your own account URL, PAT, and agent path.")

    st.subheader(":material/cloud: Streamlit-in-Snowflake (container runtime)")
    st.caption("No ``secrets.toml`` needed — Snowflake injects credentials automatically.")
    st.info(
        "**Prerequisite: two External Access Integrations (EAIs)**  \n"
        "Container runtime apps need one EAI for outbound HTTPS to the Cortex Agents "
        "REST API and one for PyPI so ``uv`` can install packages. An ``ACCOUNTADMIN`` "
        "must create them and grant them to the role that owns the Streamlit app. "
        "See ``docs/sis.md``.",
        icon=":material/lock:",
    )
    st.code(
        """
-- Run as ACCOUNTADMIN.

-- Find your account's correct hostnames (handles underscores → hyphens):
SELECT LISTAGG('''' || REPLACE(host, '_', '-') || '''', ', ') AS allowlist
FROM (
    SELECT VALUE:host::VARCHAR AS host
    FROM TABLE(FLATTEN(INPUT => PARSE_JSON(SYSTEM$ALLOWLIST())))
    WHERE VALUE:type::VARCHAR IN ('SNOWFLAKE_DEPLOYMENT','SNOWFLAKE_DEPLOYMENT_REGIONLESS')
    UNION ALL
    SELECT VALUE:host::VARCHAR AS host
    FROM TABLE(FLATTEN(INPUT => PARSE_JSON(SYSTEM$ALLOWLIST_PRIVATELINK())))
    WHERE VALUE:type::VARCHAR IN ('SNOWFLAKE_DEPLOYMENT','SNOWFLAKE_DEPLOYMENT_REGIONLESS')
);

-- 1. Network rule: allow outbound HTTPS to the Cortex Agents REST API.
--    Use the hostname(s) from the query above.
CREATE OR REPLACE NETWORK RULE common_db.security.cortex_agents_api_rule
  TYPE       = HOST_PORT
  MODE       = EGRESS
  VALUE_LIST = ('xy12345.us-east-1.snowflakecomputing.com',
                'myorg-myaccount.snowflakecomputing.com',
                'xy12345.us-east-1.privatelink.snowflakecomputing.com',
                'myorg-myaccount.privatelink.snowflakecomputing.com');  -- ← paste your allowlist result

-- 2. EAI for the Cortex Agents REST API.
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION cortex_agents_api_eai
  ALLOWED_NETWORK_RULES = (common_db.security.cortex_agents_api_rule)
  ENABLED = TRUE;

-- 3. EAI for PyPI, using Snowflake's managed network rule.
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION pypi_eai
  ALLOWED_NETWORK_RULES = (snowflake.external_access.pypi_rule)
  ENABLED = TRUE;

-- 4. Grant usage to the role that owns the Streamlit app.
GRANT USAGE ON INTEGRATION cortex_agents_api_eai TO ROLE app_owner_role;
GRANT USAGE ON INTEGRATION pypi_eai TO ROLE app_owner_role;

-- 5. Attach both EAIs to the app.
--    Option A — Workspaces UI: in the Deploy dialog open the Network tab
--               and add both integrations.
--    Option B — SQL (run as the app-owner role):
ALTER STREAMLIT my_db.my_schema.my_app
  SET EXTERNAL_ACCESS_INTEGRATIONS = (cortex_agents_api_eai, pypi_eai);
""".strip(),
        language="sql",
    )
    st.code(
        """
import streamlit as st
from streamlit_cortex_agents.chat import CortexAgentChat
from streamlit_cortex_agents.client.auth import SiSContainerAuth, account_url_from_env

AGENT_PATH = "MY_DB.MY_SCHEMA.MY_AGENT"

st.set_page_config(layout="wide")
st.title("My Agent")

CortexAgentChat(
    account_url=account_url_from_env(),  # reads SNOWFLAKE_HOST env var
    auth=SiSContainerAuth(),             # reads /snowflake/session/token
    agent_path=AGENT_PATH,
    show_thinking=True,      # set False to hide agent reasoning steps
    show_tool_status=True,   # set False to hide tool-execution spinners
).render()
""".strip(),
        language="python",
    )

    st.divider()
    st.subheader(":material/chat: Full page")
    st.caption("The entire Streamlit page is the chatbot. Default mode.")
    st.code(
        """
import streamlit as st
from streamlit_cortex_agents.chat import CortexAgentChat

SNOWFLAKE_ACCOUNT_URL = st.secrets["SNOWFLAKE_ACCOUNT_URL"]
SNOWFLAKE_PAT         = st.secrets["SNOWFLAKE_PAT"]
AGENT_PATH            = "MY_DB.MY_SCHEMA.MY_AGENT"

st.set_page_config(layout="wide")
st.title("My Agent")

CortexAgentChat(
    account_url=SNOWFLAKE_ACCOUNT_URL,
    auth=SNOWFLAKE_PAT,
    agent_path=AGENT_PATH,
    show_thinking=True,      # set False to hide agent reasoning steps
    show_tool_status=True,   # set False to hide tool-execution spinners
).render()
""".strip(),
        language="python",
    )

    st.divider()
    st.subheader(":material/view_sidebar: Embedded")
    st.caption("Chat in a fixed-height container alongside dashboard content.")
    st.code(
        """
import streamlit as st
from streamlit_cortex_agents.chat import CortexAgentChat

SNOWFLAKE_ACCOUNT_URL = st.secrets["SNOWFLAKE_ACCOUNT_URL"]
SNOWFLAKE_PAT         = st.secrets["SNOWFLAKE_PAT"]
AGENT_PATH            = "MY_DB.MY_SCHEMA.MY_AGENT"

st.set_page_config(layout="wide")
st.title("Sales Dashboard")

dash_col, chat_col = st.columns([3, 2], gap="large")

with dash_col:
    # ... your charts and tables ...
    st.bar_chart({"Q1": 100, "Q2": 120, "Q3": 115, "Q4": 140})

with chat_col:
    st.subheader(":material/smart_toy: Ask the agent")
    CortexAgentChat(
        account_url=SNOWFLAKE_ACCOUNT_URL,
        auth=SNOWFLAKE_PAT,
        agent_path=AGENT_PATH,
        mode="embedded",
        height=500,
        session_key_prefix="_ca_dash",
        show_thinking=True,      # set False to hide agent reasoning steps
        show_tool_status=True,   # set False to hide tool-execution spinners
    ).render()
""".strip(),
        language="python",
    )

    st.divider()
    st.subheader(":material/open_in_new: Dialog")
    st.caption(
        "Chat opens as a modal overlay when the user clicks a button. Uses "
        "``mode=\"embedded\"`` inside ``@st.dialog``. A session state flag keeps the "
        "dialog open across the chatbot's reruns, and ``dismissible=False`` stops a "
        "click outside from closing it."
    )
    st.code(
        """
import streamlit as st
from streamlit_cortex_agents.chat import CortexAgentChat

SNOWFLAKE_ACCOUNT_URL = st.secrets["SNOWFLAKE_ACCOUNT_URL"]
SNOWFLAKE_PAT         = st.secrets["SNOWFLAKE_PAT"]
AGENT_PATH            = "MY_DB.MY_SCHEMA.MY_AGENT"

st.set_page_config(layout="wide")
st.title("Sales Dashboard")

# Keep the dialog open across the chatbot's reruns.
if "chat_dialog_open" not in st.session_state:
    st.session_state.chat_dialog_open = False

# Pre-seed messages so st.chat_input renders on the first dialog open.
st.session_state.setdefault("_dlg_messages", [])

@st.dialog("Ask the agent", width="large", dismissible=False)
def _chat_dialog():
    if st.button("Close", icon=":material/close:", type="tertiary"):
        st.session_state.chat_dialog_open = False
        st.rerun()
    CortexAgentChat(
        account_url=SNOWFLAKE_ACCOUNT_URL,
        auth=SNOWFLAKE_PAT,
        agent_path=AGENT_PATH,
        mode="embedded",
        height="calc(100vh - 440px)",
        session_key_prefix="_dlg",
        show_thinking=True,      # set False to hide agent reasoning steps
        show_tool_status=True,   # set False to hide tool-execution spinners
    ).render()

# ... your dashboard content ...

if st.button("Ask the agent", icon=":material/chat:", type="primary"):
    st.session_state.chat_dialog_open = True

# Open the dialog last, after all other page content.
if st.session_state.chat_dialog_open:
    _chat_dialog()
""".strip(),
        language="python",
    )

    _footer()


# ---------------------------------------------------------------------------
# Navigation
# ---------------------------------------------------------------------------

pg = st.navigation(
    [
        st.Page(page_fullpage, title="Full page", icon=":material/chat:",         default=True),
        st.Page(page_embedded, title="Embedded",  icon=":material/view_sidebar:"),
        st.Page(page_dialog,   title="Dialog",    icon=":material/open_in_new:"),
        st.Page(page_code,     title="Code",       icon=":material/code:"),
    ],
    position="top",
)
pg.run()
